// Country -> currency codes. Auto-generated from mledoze/countries, do NOT hand-edit.
// Regenerate with tools/gen-country-currencies.py
//
// Data (c) mledoze/countries contributors, licensed ODbL 1.0:
//   https://github.com/mledoze/countries  https://opendatacommons.org/licenses/odbl/1-0/
//
// WHY VENDORED AND NOT FETCHED: the new-country banner has to fire the instant a
// stop is saved, offline included. A compile-time constant does that with no
// query, no cache and no failure mode. These values change roughly once a decade.
//
// NOT 1:1 - 20 countries use several currencies (Cambodia genuinely runs on both
// KHR and USD), so every value is an array and all of them join the watchlist.
//
// Keys are BOTH ISO-3166 alpha-2 (uppercase) and lowercased COMMON country names,
// because trip segments store the country as a display name. Official names are
// deliberately absent. Always look up via countryCurrencies().

export const COUNTRY_CURRENCIES: Record<string, readonly string[]> = {
  AD: ["EUR"],
  AE: ["AED"],
  AF: ["AFN"],
  AG: ["XCD"],
  AI: ["XCD"],
  AL: ["ALL"],
  AM: ["AMD"],
  AO: ["AOA"],
  AR: ["ARS"],
  AS: ["USD"],
  AT: ["EUR"],
  AU: ["AUD"],
  AW: ["AWG"],
  AX: ["EUR"],
  AZ: ["AZN"],
  BA: ["BAM"],
  BB: ["BBD"],
  BD: ["BDT"],
  BE: ["EUR"],
  BF: ["XOF"],
  BG: ["EUR"],
  BH: ["BHD"],
  BI: ["BIF"],
  BJ: ["XOF"],
  BL: ["EUR"],
  BM: ["BMD"],
  BN: ["BND", "SGD"],
  BO: ["BOB"],
  BQ: ["USD"],
  BR: ["BRL"],
  BS: ["BSD", "USD"],
  BT: ["BTN", "INR"],
  BW: ["BWP"],
  BY: ["BYN"],
  BZ: ["BZD"],
  CA: ["CAD"],
  CC: ["AUD"],
  CD: ["CDF"],
  CF: ["XAF"],
  CG: ["XAF"],
  CH: ["CHF"],
  CI: ["XOF"],
  CK: ["CKD", "NZD"],
  CL: ["CLP"],
  CM: ["XAF"],
  CN: ["CNY"],
  CO: ["COP"],
  CR: ["CRC"],
  CU: ["CUC", "CUP"],
  CV: ["CVE"],
  CW: ["ANG"],
  CX: ["AUD"],
  CY: ["EUR"],
  CZ: ["CZK"],
  DE: ["EUR"],
  DJ: ["DJF"],
  DK: ["DKK"],
  DM: ["XCD"],
  DO: ["DOP"],
  DZ: ["DZD"],
  EC: ["USD"],
  EE: ["EUR"],
  EG: ["EGP"],
  EH: ["DZD", "MAD", "MRU"],
  ER: ["ERN"],
  ES: ["EUR"],
  ET: ["ETB"],
  FI: ["EUR"],
  FJ: ["FJD"],
  FK: ["FKP"],
  FO: ["DKK", "FOK"],
  FR: ["EUR"],
  GA: ["XAF"],
  GB: ["GBP"],
  GD: ["XCD"],
  GE: ["GEL"],
  GF: ["EUR"],
  GG: ["GBP", "GGP"],
  GH: ["GHS"],
  GI: ["GIP"],
  GL: ["DKK"],
  GM: ["GMD"],
  GN: ["GNF"],
  GP: ["EUR"],
  GQ: ["XAF"],
  GR: ["EUR"],
  GS: ["SHP"],
  GT: ["GTQ"],
  GU: ["USD"],
  GW: ["XOF"],
  GY: ["GYD"],
  HK: ["HKD"],
  HN: ["HNL"],
  HR: ["EUR"],
  HT: ["HTG"],
  HU: ["HUF"],
  ID: ["IDR"],
  IE: ["EUR"],
  IL: ["ILS"],
  IM: ["GBP", "IMP"],
  IN: ["INR"],
  IO: ["USD"],
  IQ: ["IQD"],
  IR: ["IRR"],
  IS: ["ISK"],
  IT: ["EUR"],
  JE: ["GBP", "JEP"],
  JM: ["JMD"],
  JO: ["JOD"],
  JP: ["JPY"],
  KE: ["KES"],
  KG: ["KGS"],
  KH: ["KHR", "USD"],
  KI: ["AUD", "KID"],
  KM: ["KMF"],
  KN: ["XCD"],
  KP: ["KPW"],
  KR: ["KRW"],
  KW: ["KWD"],
  KY: ["KYD"],
  KZ: ["KZT"],
  LA: ["LAK"],
  LB: ["LBP"],
  LC: ["XCD"],
  LI: ["CHF"],
  LK: ["LKR"],
  LR: ["LRD"],
  LS: ["LSL", "ZAR"],
  LT: ["EUR"],
  LU: ["EUR"],
  LV: ["EUR"],
  LY: ["LYD"],
  MA: ["MAD"],
  MC: ["EUR"],
  MD: ["MDL"],
  ME: ["EUR"],
  MF: ["EUR"],
  MG: ["MGA"],
  MH: ["USD"],
  MK: ["MKD"],
  ML: ["XOF"],
  MM: ["MMK"],
  MN: ["MNT"],
  MO: ["MOP"],
  MP: ["USD"],
  MQ: ["EUR"],
  MR: ["MRU"],
  MS: ["XCD"],
  MT: ["EUR"],
  MU: ["MUR"],
  MV: ["MVR"],
  MW: ["MWK"],
  MX: ["MXN"],
  MY: ["MYR"],
  MZ: ["MZN"],
  NA: ["NAD", "ZAR"],
  NC: ["XPF"],
  NE: ["XOF"],
  NF: ["AUD"],
  NG: ["NGN"],
  NI: ["NIO"],
  NL: ["EUR"],
  NO: ["NOK"],
  NP: ["NPR"],
  NR: ["AUD"],
  NU: ["NZD"],
  NZ: ["NZD"],
  OM: ["OMR"],
  PA: ["PAB", "USD"],
  PE: ["PEN"],
  PF: ["XPF"],
  PG: ["PGK"],
  PH: ["PHP"],
  PK: ["PKR"],
  PL: ["PLN"],
  PM: ["EUR"],
  PN: ["NZD"],
  PR: ["USD"],
  PS: ["EGP", "ILS", "JOD"],
  PT: ["EUR"],
  PW: ["USD"],
  PY: ["PYG"],
  QA: ["QAR"],
  RE: ["EUR"],
  RO: ["RON"],
  RS: ["RSD"],
  RU: ["RUB"],
  RW: ["RWF"],
  SA: ["SAR"],
  SB: ["SBD"],
  SC: ["SCR"],
  SD: ["SDG"],
  SE: ["SEK"],
  SG: ["SGD"],
  SH: ["GBP", "SHP"],
  SI: ["EUR"],
  SJ: ["NOK"],
  SK: ["EUR"],
  SL: ["SLE"],
  SM: ["EUR"],
  SN: ["XOF"],
  SO: ["SOS"],
  SR: ["SRD"],
  SS: ["SSP"],
  ST: ["STN"],
  SV: ["USD"],
  SX: ["ANG"],
  SY: ["SYP"],
  SZ: ["SZL", "ZAR"],
  TC: ["USD"],
  TD: ["XAF"],
  TF: ["EUR"],
  TG: ["XOF"],
  TH: ["THB"],
  TJ: ["TJS"],
  TK: ["NZD"],
  TL: ["USD"],
  TM: ["TMT"],
  TN: ["TND"],
  TO: ["TOP"],
  TR: ["TRY"],
  TT: ["TTD"],
  TV: ["AUD", "TVD"],
  TW: ["TWD"],
  TZ: ["TZS"],
  UA: ["UAH"],
  UG: ["UGX"],
  UM: ["USD"],
  US: ["USD"],
  UY: ["UYU"],
  UZ: ["UZS"],
  VA: ["EUR"],
  VC: ["XCD"],
  VE: ["VES"],
  VG: ["USD"],
  VI: ["USD"],
  VN: ["VND"],
  VU: ["VUV"],
  WF: ["XPF"],
  WS: ["WST"],
  XK: ["EUR"],
  YE: ["YER"],
  YT: ["EUR"],
  ZA: ["ZAR"],
  ZM: ["ZMW"],
  ZW: ["USD", "ZWG"],

  // Indexed by name too - trip segments store the country as a display name.
  "afghanistan": ["AFN"],
  "albania": ["ALL"],
  "algeria": ["DZD"],
  "american samoa": ["USD"],
  "andorra": ["EUR"],
  "angola": ["AOA"],
  "anguilla": ["XCD"],
  "antigua and barbuda": ["XCD"],
  "argentina": ["ARS"],
  "armenia": ["AMD"],
  "aruba": ["AWG"],
  "australia": ["AUD"],
  "austria": ["EUR"],
  "azerbaijan": ["AZN"],
  "bahamas": ["BSD", "USD"],
  "bahrain": ["BHD"],
  "bangladesh": ["BDT"],
  "barbados": ["BBD"],
  "belarus": ["BYN"],
  "belgium": ["EUR"],
  "belize": ["BZD"],
  "benin": ["XOF"],
  "bermuda": ["BMD"],
  "bhutan": ["BTN", "INR"],
  "bolivia": ["BOB"],
  "bosnia and herzegovina": ["BAM"],
  "botswana": ["BWP"],
  "brazil": ["BRL"],
  "british indian ocean territory": ["USD"],
  "british virgin islands": ["USD"],
  "brunei": ["BND", "SGD"],
  "bulgaria": ["EUR"],
  "burkina faso": ["XOF"],
  "burundi": ["BIF"],
  "cambodia": ["KHR", "USD"],
  "cameroon": ["XAF"],
  "canada": ["CAD"],
  "cape verde": ["CVE"],
  "caribbean netherlands": ["USD"],
  "cayman islands": ["KYD"],
  "central african republic": ["XAF"],
  "chad": ["XAF"],
  "chile": ["CLP"],
  "china": ["CNY"],
  "christmas island": ["AUD"],
  "cocos (keeling) islands": ["AUD"],
  "colombia": ["COP"],
  "comoros": ["KMF"],
  "congo": ["XAF"],
  "cook islands": ["CKD", "NZD"],
  "costa rica": ["CRC"],
  "croatia": ["EUR"],
  "cuba": ["CUC", "CUP"],
  "curaçao": ["ANG"],
  "cyprus": ["EUR"],
  "czechia": ["CZK"],
  "denmark": ["DKK"],
  "djibouti": ["DJF"],
  "dominica": ["XCD"],
  "dominican republic": ["DOP"],
  "dr congo": ["CDF"],
  "ecuador": ["USD"],
  "egypt": ["EGP"],
  "el salvador": ["USD"],
  "equatorial guinea": ["XAF"],
  "eritrea": ["ERN"],
  "estonia": ["EUR"],
  "eswatini": ["SZL", "ZAR"],
  "ethiopia": ["ETB"],
  "falkland islands": ["FKP"],
  "faroe islands": ["DKK", "FOK"],
  "fiji": ["FJD"],
  "finland": ["EUR"],
  "france": ["EUR"],
  "french guiana": ["EUR"],
  "french polynesia": ["XPF"],
  "french southern and antarctic lands": ["EUR"],
  "gabon": ["XAF"],
  "gambia": ["GMD"],
  "georgia": ["GEL"],
  "germany": ["EUR"],
  "ghana": ["GHS"],
  "gibraltar": ["GIP"],
  "greece": ["EUR"],
  "greenland": ["DKK"],
  "grenada": ["XCD"],
  "guadeloupe": ["EUR"],
  "guam": ["USD"],
  "guatemala": ["GTQ"],
  "guernsey": ["GBP", "GGP"],
  "guinea": ["GNF"],
  "guinea-bissau": ["XOF"],
  "guyana": ["GYD"],
  "haiti": ["HTG"],
  "honduras": ["HNL"],
  "hong kong": ["HKD"],
  "hungary": ["HUF"],
  "iceland": ["ISK"],
  "india": ["INR"],
  "indonesia": ["IDR"],
  "iran": ["IRR"],
  "iraq": ["IQD"],
  "ireland": ["EUR"],
  "isle of man": ["GBP", "IMP"],
  "israel": ["ILS"],
  "italy": ["EUR"],
  "ivory coast": ["XOF"],
  "jamaica": ["JMD"],
  "japan": ["JPY"],
  "jersey": ["GBP", "JEP"],
  "jordan": ["JOD"],
  "kazakhstan": ["KZT"],
  "kenya": ["KES"],
  "kiribati": ["AUD", "KID"],
  "kosovo": ["EUR"],
  "kuwait": ["KWD"],
  "kyrgyzstan": ["KGS"],
  "laos": ["LAK"],
  "latvia": ["EUR"],
  "lebanon": ["LBP"],
  "lesotho": ["LSL", "ZAR"],
  "liberia": ["LRD"],
  "libya": ["LYD"],
  "liechtenstein": ["CHF"],
  "lithuania": ["EUR"],
  "luxembourg": ["EUR"],
  "macau": ["MOP"],
  "madagascar": ["MGA"],
  "malawi": ["MWK"],
  "malaysia": ["MYR"],
  "maldives": ["MVR"],
  "mali": ["XOF"],
  "malta": ["EUR"],
  "marshall islands": ["USD"],
  "martinique": ["EUR"],
  "mauritania": ["MRU"],
  "mauritius": ["MUR"],
  "mayotte": ["EUR"],
  "mexico": ["MXN"],
  "moldova": ["MDL"],
  "monaco": ["EUR"],
  "mongolia": ["MNT"],
  "montenegro": ["EUR"],
  "montserrat": ["XCD"],
  "morocco": ["MAD"],
  "mozambique": ["MZN"],
  "myanmar": ["MMK"],
  "namibia": ["NAD", "ZAR"],
  "nauru": ["AUD"],
  "nepal": ["NPR"],
  "netherlands": ["EUR"],
  "new caledonia": ["XPF"],
  "new zealand": ["NZD"],
  "nicaragua": ["NIO"],
  "niger": ["XOF"],
  "nigeria": ["NGN"],
  "niue": ["NZD"],
  "norfolk island": ["AUD"],
  "north korea": ["KPW"],
  "north macedonia": ["MKD"],
  "northern mariana islands": ["USD"],
  "norway": ["NOK"],
  "oman": ["OMR"],
  "pakistan": ["PKR"],
  "palau": ["USD"],
  "palestine": ["EGP", "ILS", "JOD"],
  "panama": ["PAB", "USD"],
  "papua new guinea": ["PGK"],
  "paraguay": ["PYG"],
  "peru": ["PEN"],
  "philippines": ["PHP"],
  "pitcairn islands": ["NZD"],
  "poland": ["PLN"],
  "portugal": ["EUR"],
  "puerto rico": ["USD"],
  "qatar": ["QAR"],
  "romania": ["RON"],
  "russia": ["RUB"],
  "rwanda": ["RWF"],
  "réunion": ["EUR"],
  "saint barthélemy": ["EUR"],
  "saint helena, ascension and tristan da cunha": ["GBP", "SHP"],
  "saint kitts and nevis": ["XCD"],
  "saint lucia": ["XCD"],
  "saint martin": ["EUR"],
  "saint pierre and miquelon": ["EUR"],
  "saint vincent and the grenadines": ["XCD"],
  "samoa": ["WST"],
  "san marino": ["EUR"],
  "saudi arabia": ["SAR"],
  "senegal": ["XOF"],
  "serbia": ["RSD"],
  "seychelles": ["SCR"],
  "sierra leone": ["SLE"],
  "singapore": ["SGD"],
  "sint maarten": ["ANG"],
  "slovakia": ["EUR"],
  "slovenia": ["EUR"],
  "solomon islands": ["SBD"],
  "somalia": ["SOS"],
  "south africa": ["ZAR"],
  "south georgia": ["SHP"],
  "south korea": ["KRW"],
  "south sudan": ["SSP"],
  "spain": ["EUR"],
  "sri lanka": ["LKR"],
  "sudan": ["SDG"],
  "suriname": ["SRD"],
  "svalbard and jan mayen": ["NOK"],
  "sweden": ["SEK"],
  "switzerland": ["CHF"],
  "syria": ["SYP"],
  "são tomé and príncipe": ["STN"],
  "taiwan": ["TWD"],
  "tajikistan": ["TJS"],
  "tanzania": ["TZS"],
  "thailand": ["THB"],
  "timor-leste": ["USD"],
  "togo": ["XOF"],
  "tokelau": ["NZD"],
  "tonga": ["TOP"],
  "trinidad and tobago": ["TTD"],
  "tunisia": ["TND"],
  "turkmenistan": ["TMT"],
  "turks and caicos islands": ["USD"],
  "tuvalu": ["AUD", "TVD"],
  "türkiye": ["TRY"],
  "uganda": ["UGX"],
  "ukraine": ["UAH"],
  "united arab emirates": ["AED"],
  "united kingdom": ["GBP"],
  "united states": ["USD"],
  "united states minor outlying islands": ["USD"],
  "united states virgin islands": ["USD"],
  "uruguay": ["UYU"],
  "uzbekistan": ["UZS"],
  "vanuatu": ["VUV"],
  "vatican city": ["EUR"],
  "venezuela": ["VES"],
  "vietnam": ["VND"],
  "wallis and futuna": ["XPF"],
  "western sahara": ["DZD", "MAD", "MRU"],
  "yemen": ["YER"],
  "zambia": ["ZMW"],
  "zimbabwe": ["USD", "ZWG"],
  "åland islands": ["EUR"],
}

/** ISO2 -> common country name, for the inverse lookup and banner copy. */
const COUNTRY_NAME: Record<string, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Caribbean Netherlands",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "DR Congo",
  CF: "Central African Republic",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Ivory Coast",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macau",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "São Tomé and Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern and Antarctic Lands",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "United States Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  XK: "Kosovo",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
}

/** Currencies used by a country, given an ISO2 code or a country name. Empty if unknown. */
export function countryCurrencies(countryOrIso: string | undefined | null): readonly string[] {
  if (!countryOrIso) return []
  const raw = countryOrIso.trim()
  return COUNTRY_CURRENCIES[raw.toUpperCase()] ?? COUNTRY_CURRENCIES[raw.toLowerCase()] ?? []
}

// Built on first use rather than shipped: the inverse is the same data again, and
// only the Settings panel ever needs it.
let inverse: Map<string, string[]> | null = null

/** Countries using a currency, by common name. Powers the "also accepted in" line. */
export function currencyCountries(code: string): string[] {
  if (!inverse) {
    inverse = new Map()
    for (const [iso2, name] of Object.entries(COUNTRY_NAME)) {
      for (const c of COUNTRY_CURRENCIES[iso2] ?? []) {
        const list = inverse.get(c) ?? []
        list.push(name)
        inverse.set(c, list)
      }
    }
    for (const list of inverse.values()) list.sort()
  }
  return inverse.get(code) ?? []
}
