// GENERATED by tools/tokens.mjs from design/tokens.json — do not edit by hand.
// The web app reads the same file (product/src/app/globals.css), so a colour
// changed there changes here on the next generator run.

import SwiftUI

/// Livhold colour tokens. Names match the CSS custom properties (`--ac` → `Palette.ac`).
enum Palette {
    static let canvas = Color(light: RGBA(240, 238, 233), dark: RGBA(18, 22, 26))
    static let pg = Color(light: RGBA(232, 247, 238), dark: RGBA(22, 26, 24))
    static let sf = Color(light: RGBA(255, 255, 255), dark: RGBA(31, 38, 34))
    static let `in` = Color(light: RGBA(247, 250, 248), dark: RGBA(25, 32, 28))
    static let tx = Color(light: RGBA(31, 42, 36), dark: RGBA(216, 224, 229))
    static let tx2 = Color(light: RGBA(63, 90, 62), dark: RGBA(168, 181, 168))
    static let tx3 = Color(light: RGBA(31, 42, 36, 0.5), dark: RGBA(216, 224, 229, 0.5))
    static let ac = Color(light: RGBA(63, 90, 62), dark: RGBA(127, 163, 125))
    static let on = Color(light: RGBA(255, 255, 255), dark: RGBA(16, 22, 15))
    static let acSoft = Color(light: RGBA(63, 90, 62, 0.11), dark: RGBA(127, 163, 125, 0.16))
    static let acLine = Color(light: RGBA(63, 90, 62, 0.45), dark: RGBA(127, 163, 125, 0.5))
    static let ac2 = Color(light: RGBA(169, 76, 90), dark: RGBA(208, 135, 149))
    static let ac2Deep = Color(light: RGBA(147, 64, 76), dark: RGBA(222, 155, 167))
    static let ac2Line = Color(light: RGBA(169, 76, 90, 0.45), dark: RGBA(208, 135, 149, 0.5))
    static let ac2Soft = Color(light: RGBA(169, 76, 90, 0.1), dark: RGBA(208, 135, 149, 0.14))
    static let warn = Color(light: RGBA(138, 100, 32), dark: RGBA(217, 168, 92))
    static let warnLine = Color(light: RGBA(138, 100, 32, 0.55), dark: RGBA(217, 168, 92, 0.6))
    static let warnSoft = Color(light: RGBA(138, 100, 32, 0.08), dark: RGBA(217, 168, 92, 0.13))
    static let tag = Color(light: RGBA(228, 238, 230), dark: RGBA(201, 214, 234, 0.14))
    static let tagInk = Color(light: RGBA(43, 58, 74), dark: RGBA(201, 214, 234))
    static let ph = Color(light: RGBA(220, 230, 221), dark: RGBA(39, 48, 43))
    static let ln = Color(light: RGBA(31, 42, 36, 0.11), dark: RGBA(216, 224, 229, 0.1))
    static let ln2 = Color(light: RGBA(31, 42, 36, 0.16), dark: RGBA(216, 224, 229, 0.16))
    static let ln3 = Color(light: RGBA(31, 42, 36, 0.24), dark: RGBA(216, 224, 229, 0.26))
    static let tr = Color(light: RGBA(31, 42, 36, 0.13), dark: RGBA(216, 224, 229, 0.14))
    static let fill = Color(light: RGBA(31, 42, 36, 0.08), dark: RGBA(216, 224, 229, 0.07))
    static let fill2 = Color(light: RGBA(31, 42, 36, 0.1), dark: RGBA(216, 224, 229, 0.1))
    // palette extras + budget category (Stays = --ac, Transport = --ac2, Extras = --warn)
    static let catDaily = Color(light: RGBA(108, 140, 207), dark: RGBA(108, 140, 207))
    // Money chart families (round-two design, 2026-09-13): groceries & shops, activities
    static let catGrocery = Color(light: RGBA(143, 168, 138), dark: RGBA(159, 184, 154))
    static let catActivity = Color(light: RGBA(201, 138, 99), dark: RGBA(217, 160, 124))
    static let sage = Color(light: RGBA(201, 212, 186), dark: RGBA(201, 212, 186))
    static let paleBlue = Color(light: RGBA(174, 195, 214), dark: RGBA(174, 195, 214))
    static let paper = Color(light: RGBA(245, 242, 234), dark: RGBA(245, 242, 234))
    static let blush = Color(light: RGBA(247, 230, 233), dark: RGBA(247, 230, 233))
    // landscape washes — 2a login/invite only, 2b milestones; grammar in handoff README
    static let washInk = Color(light: RGBA(31, 42, 36), dark: RGBA(216, 224, 229))

    /// Every token with its CSS name, in file order — for the gallery swatches.
    static let all: [(name: String, color: Color)] = [
        ("canvas", canvas),
        ("pg", pg),
        ("sf", sf),
        ("in", `in`),
        ("tx", tx),
        ("tx2", tx2),
        ("tx3", tx3),
        ("ac", ac),
        ("on", on),
        ("acSoft", acSoft),
        ("acLine", acLine),
        ("ac2", ac2),
        ("ac2Deep", ac2Deep),
        ("ac2Line", ac2Line),
        ("ac2Soft", ac2Soft),
        ("warn", warn),
        ("warnLine", warnLine),
        ("warnSoft", warnSoft),
        ("tag", tag),
        ("tagInk", tagInk),
        ("ph", ph),
        ("ln", ln),
        ("ln2", ln2),
        ("ln3", ln3),
        ("tr", tr),
        ("fill", fill),
        ("fill2", fill2),
        ("catDaily", catDaily),
        ("catGrocery", catGrocery),
        ("catActivity", catActivity),
        ("sage", sage),
        ("paleBlue", paleBlue),
        ("paper", paper),
        ("blush", blush),
        ("washInk", washInk),
    ]
}

/// Corner radii, in points (web uses the same numbers in px).
enum Radius {
    static let r: CGFloat = 22
    static let rCtl: CGFloat = 20
}

/// Landscape washes: an asset-catalog image (light + dark variant) over a base colour.
enum Wash {
    static let login = WashStyle(image: "washLogin", base: Color(light: RGBA(240, 239, 231), dark: RGBA(22, 26, 24)))
    static let light = WashStyle(image: "washLight", base: Color(light: RGBA(240, 239, 231), dark: RGBA(22, 26, 24)))
}

/// Font family names as registered from the bundled font files.
enum FontFamily {
    /// body, controls, figures (tabular)
    static let sans = "Work Sans"
    /// headings and display
    static let serif = "Lora"
}
