#!/usr/bin/env node
// The iOS globe's map data (#166): Natural Earth 50m, from the world-atlas package,
// turned into one small binary file the app reads at launch, plus the names.
//
//   npm i --prefix /tmp/geo topojson-client@3 d3-geo@3 world-atlas@2
//   NODE_PATH=/tmp/geo/node_modules node tools/globe-data.mjs
//
// Writes ios/Livhold/Globe/Data/globe50m.bin and globe-names.json. Run again when
// tools/globe-names.json changes (a name, a Hungarian name, a zoom level).
//
// globe50m.bin, little-endian:
//   "LVG1"
//   u32 countries; each: u32 rings; each ring: u32 points, then f32 lon, f32 lat per point
//   u32 coast lines (the outline of the land, no borders); each: u32 points, f32 pairs
//   u32 border lines (between two countries); each: u32 points, f32 pairs
// Country i in the file is country i in globe-names.json's "countries".

import { createRequire } from 'node:module'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const topo = require('topojson-client')
const d3 = require('d3-geo')
const world = require('world-atlas/countries-50m.json')

const here = dirname(fileURLToPath(import.meta.url))
const src = JSON.parse(readFileSync(join(here, 'globe-names.json'), 'utf8'))
const outDir = join(here, '..', 'ios', 'Livhold', 'Globe', 'Data')
mkdirSync(outDir, { recursive: true })

const countries = topo.feature(world, world.objects.countries).features
const coast = topo.mesh(world, world.objects.countries, (a, b) => a === b)
const borders = topo.mesh(world, world.objects.countries, (a, b) => a !== b)

const smallArea = (g) => { const a = d3.geoArea(g); return a > 2 * Math.PI ? 4 * Math.PI - a : a }

const chunks = []
const u32 = (n) => { const b = Buffer.alloc(4); b.writeUInt32LE(n); chunks.push(b) }
const line = (pts) => {
  u32(pts.length)
  const b = Buffer.alloc(pts.length * 8)
  pts.forEach(([lon, lat], i) => { b.writeFloatLE(lon, i * 8); b.writeFloatLE(lat, i * 8 + 4) })
  chunks.push(b)
}

chunks.push(Buffer.from('LVG1'))
u32(countries.length)
const table = []
let points = 0
for (const f of countries) {
  const g = f.geometry
  const polys = !g ? [] : g.type === 'MultiPolygon' ? g.coordinates : [g.coordinates]
  const rings = polys.flat()
  u32(rings.length)
  for (const r of rings) { line(r); points += r.length }

  const raw = f.properties?.name ?? ''
  const skip = !raw || src.anchor[raw] === null || src.skip.includes(raw)
  let at = src.anchor[raw]
  if (!skip && !at) {
    let best = null, ba = -1
    for (const p of polys) { const a = smallArea({ type: 'Polygon', coordinates: p }); if (a > ba) { ba = a; best = p } }
    at = best ? d3.geoCentroid({ type: 'Polygon', coordinates: best }) : null
  }
  const name = src.rename[raw] ?? raw
  table.push({
    id: f.id ?? null,
    name: name.toUpperCase(),
    hu: (src.huCountry[raw] ?? name).toLocaleUpperCase('hu'),
    at: skip || !at ? null : [+at[0].toFixed(3), +at[1].toFixed(3)],
    size: g ? +Math.sqrt(smallArea(f)).toFixed(5) : 0,
  })
}
const lines = (mesh) => { u32(mesh.coordinates.length); for (const l of mesh.coordinates) { line(l); points += l.length } }
lines(coast)
lines(borders)

const bin = Buffer.concat(chunks)
writeFileSync(join(outDir, 'globe50m.bin'), bin)

const tr = (t) => src.huPlace[t] ?? t
const names = {
  _source: 'Generated by tools/globe-data.mjs from tools/globe-names.json and Natural Earth 50m (world-atlas). Do not edit by hand.',
  countries: table,
  continents: src.continents.map(([t, lat, lng]) => ({ en: t, hu: tr(t), lat, lng })),
  oceans: src.oceans.map(([t, lat, lng, span]) => ({ en: t, hu: tr(t), lat, lng, span })),
  places: src.places.map(([t, lat, lng, kmin, kind]) => ({ en: t, hu: tr(t), lat, lng, kmin, kind })),
}
writeFileSync(join(outDir, 'globe-names.json'), JSON.stringify(names))
console.log(`globe50m.bin ${(bin.length / 1024).toFixed(0)} KB, ${points} points, ${countries.length} countries`)
