#!/usr/bin/env node
// Builds the list form for the landing page (landing/) from livhold-journey-form.html,
// the preview Petra signed off: the part between the COPY markers, with
// CONFIG.endpoint filled in, goes into landing/public/index.html (between its
// lh-form markers) and into docs/landing-form/livhold-journey-form.paste.html. The preview keeps its empty endpoint
// (nothing is sent from a preview, and its state buttons keep working); the
// paste never ships without one (an empty endpoint fakes success).
//
//   node tools/landing-form.mjs
//
// Edit the preview, re-run, commit both.
import { readFileSync, writeFileSync } from 'node:fs'

const SRC = new URL('../docs/landing-form/livhold-journey-form.html', import.meta.url)
const OUT = new URL('../docs/landing-form/livhold-journey-form.paste.html', import.meta.url)
const PAGE = new URL('../landing/public/index.html', import.meta.url)
// The app's endpoint (product/src/app/api/journey-signup/route.ts), on the app's own
// address since step 3 of docs/APP-MOVE-BRIEF.md: from step 5 livhold.com is the landing
// page, and a redirect is something a cross-origin POST cannot follow.
const ENDPOINT = 'https://app.livhold.com/api/journey-signup'

const html = readFileSync(SRC, 'utf8')
const from = html.indexOf('<!-- ===================== COPY FROM HERE')
const to = html.indexOf('<!-- ===================== COPY TO HERE')
if (from < 0 || to < 0) throw new Error('COPY FROM HERE / COPY TO HERE markers not found')
const block = html.slice(html.indexOf('\n', from) + 1, to)

const filled = block.replace(/endpoint:(\s*)"",/, (_, ws) => `endpoint:${ws}"${ENDPOINT}",`)
if (filled === block) throw new Error('CONFIG.endpoint not found, or no longer empty, in the preview')

writeFileSync(
  OUT,
  `<!-- Generated by tools/landing-form.mjs from livhold-journey-form.html: edit that file and re-run, never this one. -->\n` +
    filled,
)
console.log(`wrote ${OUT.pathname}`)

const page = readFileSync(PAGE, 'utf8')
const start = page.indexOf('<!-- lh-form:start')
const end = page.indexOf('<!-- lh-form:end -->')
if (start < 0 || end < start) throw new Error('lh-form:start / lh-form:end markers not found in the landing page')
const startEnd = page.indexOf('-->', start) + 3
writeFileSync(PAGE, page.slice(0, startEnd) + '\n' + filled + page.slice(end))
console.log(`wrote ${PAGE.pathname}`)
