#!/usr/bin/env node
// Builds docs/landing-form/livhold-journey-form.paste.html, the block to paste
// into the hosted journey.livhold.com page, from livhold-journey-form.html,
// the preview Petra signed off. Only the part between the COPY markers goes
// out, with CONFIG.endpoint filled in. The preview keeps its empty endpoint
// (nothing is sent from a preview, and its state buttons keep working); the
// paste never ships without one (an empty endpoint fakes success).
//
//   node tools/landing-form.mjs
//
// Edit the preview, re-run, commit both.
import { readFileSync, writeFileSync } from 'node:fs'

const SRC = new URL('../docs/landing-form/livhold-journey-form.html', import.meta.url)
const OUT = new URL('../docs/landing-form/livhold-journey-form.paste.html', import.meta.url)
// The app's endpoint (product/src/app/api/journey-signup/route.ts). The apex:
// www.livhold.com answers with a redirect, which a cross-origin POST cannot follow.
const ENDPOINT = 'https://livhold.com/api/journey-signup'

const html = readFileSync(SRC, 'utf8')
const from = html.indexOf('<!-- ===================== COPY FROM HERE')
const to = html.indexOf('<!-- ===================== COPY TO HERE')
if (from < 0 || to < 0) throw new Error('COPY FROM HERE / COPY TO HERE markers not found')
const block = html.slice(html.indexOf('\n', from) + 1, to)

const filled = block.replace(/endpoint:(\s*)"",/, (_, ws) => `endpoint:${ws}"${ENDPOINT}",`)
if (filled === block) throw new Error('CONFIG.endpoint not found, or no longer empty, in the preview')

writeFileSync(
  OUT,
  `<!-- Generated by tools/landing-form.mjs from livhold-journey-form.html: edit that file and re-run, never this one. -->\n` +
    filled,
)
console.log(`wrote ${OUT.pathname}`)
