#!/usr/bin/env node
// Livhold token generator. design/tokens.json is the only hand-edited source;
// this writes the three things that must agree with it:
//
//   1. the :root / [data-theme="dark"] block in product/src/app/globals.css
//      (between the @generated:tokens markers — nothing else in the file is touched)
//   2. ios/Livhold/Theme/Tokens.swift
//   3. the wash image sets in ios/Livhold/Assets.xcassets (light + dark variant each)
//
//   node tools/tokens.mjs          write all three
//   node tools/tokens.mjs --check  exit 1 if any is stale (for CI / pre-commit)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const check = process.argv.includes('--check')
const tokens = JSON.parse(readFileSync(join(root, 'design/tokens.json'), 'utf8'))

const CSS_PATH = join(root, 'product/src/app/globals.css')
const SWIFT_PATH = join(root, 'ios/Livhold/Theme/Tokens.swift')
const ASSETS_PATH = join(root, 'ios/Livhold/Assets.xcassets')
const PUBLIC = join(root, 'product/public')
const START = '/* @generated:tokens start — edit design/tokens.json, then run `node tools/tokens.mjs` */'
const END = '/* @generated:tokens end */'

const entries = [...tokens.colors, ...tokens.washes.entries]
const cssWash = (w) => `url("${w.image}") bottom/cover no-repeat ${w.base}`
const cssValue = (v) => (typeof v === 'string' ? v : cssWash(v))

// ── 1. CSS ───────────────────────────────────────────────────────────────
function cssBlock() {
  const light = [':root {']
  for (const e of entries) {
    if (e.comment) light.push(`  /* ${e.comment} */`)
    else light.push(`  --${e.name}: ${cssValue(e.light)};`)
  }
  for (const [k, v] of Object.entries(tokens.radius)) light.push(`  --${k}: ${v}px;`)
  light.push('  /* legacy aliases — boot splash + pre-redesign screens */')
  light.push('  --background: var(--canvas);', '  --foreground: var(--tx);', '}')

  const dark = [':root[data-theme="dark"] {']
  for (const e of entries) if (e.name && e.dark) dark.push(`  --${e.name}: ${cssValue(e.dark)};`)
  dark.push('}')

  return [START, ...light, '', ...dark, END].join('\n')
}

function nextCss() {
  const css = readFileSync(CSS_PATH, 'utf8')
  const a = css.indexOf(START)
  const b = css.indexOf(END)
  if (a < 0 || b < 0) throw new Error(`globals.css: @generated:tokens markers not found`)
  return css.slice(0, a) + cssBlock() + css.slice(b + END.length)
}

// ── 2. Swift ─────────────────────────────────────────────────────────────
function rgba(v) {
  let m = /^#([0-9a-f]{6})$/i.exec(v)
  if (m) {
    const n = parseInt(m[1], 16)
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255, 1]
  }
  m = /^rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\s*\)$/.exec(v)
  if (m) return [+m[1], +m[2], +m[3], +m[4]]
  throw new Error(`tokens.json: cannot read colour "${v}"`)
}
const swiftRGBA = (v) => {
  const [r, g, b, a] = rgba(v)
  return `RGBA(${r}, ${g}, ${b}${a === 1 ? '' : `, ${a}`})`
}
// `--in` is a Swift keyword; backticks keep the name identical to the CSS one.
const SWIFT_RESERVED = new Set(['in', 'is', 'as', 'do', 'if', 'for', 'let', 'var', 'case', 'default', 'repeat', 'return'])
const swiftName = (n) => (SWIFT_RESERVED.has(n) ? `\`${n}\`` : n)
const swiftColor = (e) => `Color(light: ${swiftRGBA(e.light)}, dark: ${swiftRGBA(e.dark ?? e.light)})`

function swiftFile() {
  const out = [
    '// GENERATED by tools/tokens.mjs from design/tokens.json — do not edit by hand.',
    '// The web app reads the same file (product/src/app/globals.css), so a colour',
    '// changed there changes here on the next generator run.',
    '',
    'import SwiftUI',
    '',
    '/// Livhold colour tokens. Names match the CSS custom properties (`--ac` → `Palette.ac`).',
    'enum Palette {',
  ]
  for (const e of entries) {
    if (e.comment) out.push(`    // ${e.comment}`)
    else if (typeof e.light === 'string') out.push(`    static let ${swiftName(e.name)} = ${swiftColor(e)}`)
  }
  out.push('', '    /// Every token with its CSS name, in file order — for the gallery swatches.', '    static let all: [(name: String, color: Color)] = [')
  for (const e of entries) if (e.name && typeof e.light === 'string') out.push(`        ("${e.name}", ${swiftName(e.name)}),`)
  out.push('    ]')
  out.push('}', '', '/// Corner radii, in points (web uses the same numbers in px).', 'enum Radius {')
  for (const [k, v] of Object.entries(tokens.radius)) out.push(`    static let ${k}: CGFloat = ${v}`)
  out.push('}', '', '/// Landscape washes: an asset-catalog image (light + dark variant) over a base colour.', 'enum Wash {')
  for (const e of tokens.washes.entries) {
    if (!e.name || typeof e.light === 'string') continue
    const base = swiftColor({ light: e.light.base, dark: e.dark.base })
    out.push(`    static let ${e.name.replace(/^wash/, '').replace(/^./, (c) => c.toLowerCase())} = WashStyle(image: "${e.name}", base: ${base})`)
  }
  out.push('}', '', '/// Font family names as registered from the bundled font files.', 'enum FontFamily {')
  for (const [k, f] of Object.entries(tokens.fonts)) out.push(`    /// ${f.role}`, `    static let ${k} = "${f.family}"`)
  out.push('}', '')
  return out.join('\n')
}

// ── 3. Wash image sets ───────────────────────────────────────────────────
function washSets() {
  const files = [] // [path, contents | {copyFrom}]
  for (const e of tokens.washes.entries) {
    if (!e.name || typeof e.light === 'string') continue
    const dir = join(ASSETS_PATH, `${e.name}.imageset`)
    const name = (w, suffix) => `${e.name}${suffix}${extname(w.image)}`
    const images = [
      { filename: name(e.light, ''), idiom: 'universal' },
      {
        appearances: [{ appearance: 'luminosity', value: 'dark' }],
        filename: name(e.dark, '-dark'),
        idiom: 'universal',
      },
    ]
    files.push([join(dir, 'Contents.json'), JSON.stringify({ images, info: { author: 'xcode', version: 1 } }, null, 2) + '\n'])
    files.push([join(dir, name(e.light, '')), { copyFrom: join(PUBLIC, e.light.image) }])
    files.push([join(dir, name(e.dark, '-dark')), { copyFrom: join(PUBLIC, e.dark.image) }])
  }
  return files
}

// ── write / check ────────────────────────────────────────────────────────
const outputs = [
  [CSS_PATH, nextCss()],
  [SWIFT_PATH, swiftFile()],
  ...washSets(),
]

let stale = []
for (const [path, content] of outputs) {
  const want = typeof content === 'string' ? Buffer.from(content) : readFileSync(content.copyFrom)
  const have = existsSync(path) ? readFileSync(path) : null
  if (have && have.equals(want)) continue
  stale.push(path.slice(root.length + 1))
  if (!check) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, want)
  }
}

if (check && stale.length) {
  console.error(`Tokens are stale — run \`node tools/tokens.mjs\`:\n  ${stale.join('\n  ')}`)
  process.exit(1)
}
console.log(stale.length ? `wrote ${stale.length} file(s):\n  ${stale.join('\n  ')}` : 'tokens up to date')
