-- Assertions for migration 17. Runs in a transaction and ROLLS BACK.
begin;

\set QUIET on
\set ON_ERROR_STOP on

do $$
declare
  v_share   public.trip_shares;
  v_raw     text;
  v_view    text;
  v_sub     uuid;
  v_by_view jsonb;
  v_feed    jsonb;
  v_stats   jsonb;
begin
  select * into v_share from public.trip_shares where label = 'Family' limit 1;

  -- Mint a subscriber on that share. view_token comes from the DEFAULT, which
  -- proves a not-yet-redeployed digest function still inserts successfully.
  insert into public.digest_subscriptions
    (share_id, email, frequency, confirm_token_hash, unsub_token)
  values (v_share.id, 'assert17@test.local', 'weekly', 'x', 'unsub-assert-17')
  returning id, view_token into v_sub, v_view;

  if v_view is null or length(v_view) <> 64 then
    raise exception 'FAIL: view_token default did not fire (got %)', v_view;
  end if;
  raise notice 'OK  view_token auto-generated by DEFAULT (% chars)', length(v_view);

  -- 1. UNCONFIRMED view token already resolves (confirmation email carries it).
  v_by_view := public.shared_trip_summary(v_view);
  if v_by_view is null then
    raise exception 'FAIL: unconfirmed view token did not resolve';
  end if;
  raise notice 'OK  unconfirmed view token resolves -> tripName=%', v_by_view->>'tripName';

  -- 2. Same sanitized payload as a share token, and still no leakage.
  if v_by_view ? 'state' or v_by_view ? 'ledger' then
    raise exception 'FAIL: summary leaked raw state/ledger';
  end if;
  v_feed := public.shared_feed(v_view);
  if v_feed is null then raise exception 'FAIL: feed did not resolve for view token'; end if;
  raise notice 'OK  shared_feed via view token -> % events, no raw payload', jsonb_array_length(v_feed);

  -- 3. A bogus token still resolves to nothing.
  if public.shared_trip_summary('not-a-real-token-000') is not null then
    raise exception 'FAIL: garbage token resolved';
  end if;
  raise notice 'OK  garbage token -> null';

  -- 4. Owner stats count a confirmed subscriber, and stop counting after unsub.
  --    share_follower_stats is owner-only, so borrow the trip owner's identity.
  perform set_config('request.jwt.claims',
    json_build_object('sub', (select owner from public.trips where id = v_share.trip_id))::text, true);
  update public.digest_subscriptions set confirmed_at = now() where id = v_sub;
  select (select x->>'email' from jsonb_array_elements(public.share_follower_stats(v_share.trip_id)) x
           where (x->>'share_id')::uuid = v_share.id)::jsonb into v_stats;
  if v_stats::int < 1 then raise exception 'FAIL: confirmed subscriber not counted (got %)', v_stats; end if;
  raise notice 'OK  confirmed subscriber counted (email=%)', v_stats;

  update public.digest_subscriptions set unsubscribed_at = now() where id = v_sub;
  select (select x->>'email' from jsonb_array_elements(public.share_follower_stats(v_share.trip_id)) x
           where (x->>'share_id')::uuid = v_share.id)::jsonb into v_stats;
  if v_stats::int <> 0 then raise exception 'FAIL: unsubscribed row still counted (got %)', v_stats; end if;
  raise notice 'OK  unsubscribed subscriber no longer counted';

  -- 5. Unsubscribing stops emails but NOT access (mock 11 state 4).
  if public.shared_trip_summary(v_view) is null then
    raise exception 'FAIL: view token died on unsubscribe — access must survive';
  end if;
  raise notice 'OK  view token still resolves after unsubscribe (access survives)';

  -- 6. Pause still answers {paused,tripName} through a view token.
  update public.trip_shares set paused_at = now() where id = v_share.id;
  v_by_view := public.shared_trip_summary(v_view);
  if not coalesce((v_by_view->>'paused')::boolean, false) then
    raise exception 'FAIL: paused share leaked full summary via view token: %', v_by_view;
  end if;
  if jsonb_array_length(public.shared_feed(v_view)) <> 0 then
    raise exception 'FAIL: paused share leaked feed via view token';
  end if;
  raise notice 'OK  paused -> {paused,tripName} only, empty feed';
  update public.trip_shares set paused_at = null where id = v_share.id;

  -- 7. Revoke kills the view token dead.
  update public.trip_shares set revoked_at = now() where id = v_share.id;
  if public.shared_trip_summary(v_view) is not null then
    raise exception 'FAIL: revoked share still readable via view token';
  end if;
  raise notice 'OK  revoked share -> view token dead';
  update public.trip_shares set revoked_at = null where id = v_share.id;

  -- 8. Expiry kills it too.
  update public.trip_shares set expires_at = now() - interval '1 day' where id = v_share.id;
  if public.shared_trip_summary(v_view) is not null then
    raise exception 'FAIL: expired share still readable via view token';
  end if;
  raise notice 'OK  expired share -> view token dead';

  raise notice '--- ALL MIGRATION 17 ASSERTIONS PASSED ---';
end $$;

rollback;
